
import Providers from "./providers"
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "../components/Navbar";
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "../context/CartContext";
import { AuthProvider } from "../context/AuthContext";
import NavbarWrapper from "../components/NavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Providers>
          <AuthProvider>
            <CartProvider>
              <NavbarWrapper/>
              {children}
            </CartProvider>
          </AuthProvider>
          <Toaster 
            position="top-right"
            toastOptions={{
              style: {
                background: "#333",
                color: "#fff"
              }
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
